server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #集群版
      #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh     #路由的id，没有固定规则但需唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址,lb表示负载均衡
#          filter:
#            - AddRequestParameter=X-Request-Id, 1024 #过滤器工厂会在匹配的请求头上加上一对请求头，名为X-Request_id，值为1024
          predicates:
            - Path=/payment/get/**  #断言，路径相匹配进行路由
            - After=2020-05-20T20:22:17.275+08:00[Asia/Shanghai] #在这个时间后访问才会被匹配，
#            -同理，Before，Between(逗号分隔)
#            - Cookie=username,mxl #指定匹配cookie键username的值是mxl。crul工具
#            - Header=X-Request-Id, \d+ #请求头含有X-Request-Id属性且值为整数的正则表达式
#            - Method=GET
#            - Query=username, \d+ #请求参数

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**